// Code generated by 'yaegi extract gioui.org/io/clipboard'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/io/clipboard"
	"reflect"
)

func init() {
	Symbols["gioui.org/io/clipboard"] = map[string]reflect.Value{
		// type definitions
		"Event":   reflect.ValueOf((*clipboard.Event)(nil)),
		"ReadOp":  reflect.ValueOf((*clipboard.ReadOp)(nil)),
		"WriteOp": reflect.ValueOf((*clipboard.WriteOp)(nil)),
	}
}
