// Code generated by 'yaegi extract gioui.org/gesture'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/gesture"
	"reflect"
)

func init() {
	Symbols["gioui.org/gesture"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Both":          reflect.ValueOf(gesture.Both),
		"Horizontal":    reflect.ValueOf(gesture.Horizontal),
		"StateDragging": reflect.ValueOf(gesture.StateDragging),
		"StateFlinging": reflect.ValueOf(gesture.StateFlinging),
		"StateIdle":     reflect.ValueOf(gesture.StateIdle),
		"TypeCancel":    reflect.ValueOf(gesture.TypeCancel),
		"TypeClick":     reflect.ValueOf(gesture.TypeClick),
		"TypePress":     reflect.ValueOf(gesture.TypePress),
		"Vertical":      reflect.ValueOf(gesture.Vertical),

		// type definitions
		"Axis":        reflect.ValueOf((*gesture.Axis)(nil)),
		"Click":       reflect.ValueOf((*gesture.Click)(nil)),
		"ClickEvent":  reflect.ValueOf((*gesture.ClickEvent)(nil)),
		"ClickState":  reflect.ValueOf((*gesture.ClickState)(nil)),
		"ClickType":   reflect.ValueOf((*gesture.ClickType)(nil)),
		"Drag":        reflect.ValueOf((*gesture.Drag)(nil)),
		"Scroll":      reflect.ValueOf((*gesture.Scroll)(nil)),
		"ScrollState": reflect.ValueOf((*gesture.ScrollState)(nil)),
	}
}
