// Code generated by 'yaegi extract gioui.org/app'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/app"
	"reflect"
)

func init() {
	Symbols["gioui.org/app"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DataDir":   reflect.ValueOf(app.DataDir),
		"Main":      reflect.ValueOf(app.Main),
		"MaxSize":   reflect.ValueOf(app.MaxSize),
		"MinSize":   reflect.ValueOf(app.MinSize),
		"NewWindow": reflect.ValueOf(app.NewWindow),
		"Size":      reflect.ValueOf(app.Size),
		"Title":     reflect.ValueOf(app.Title),

		// type definitions
		"Option": reflect.ValueOf((*app.Option)(nil)),
		"Window": reflect.ValueOf((*app.Window)(nil)),
	}
}
