// Code generated by 'yaegi extract gioui.org/io/profile'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/io/profile"
	"reflect"
)

func init() {
	Symbols["gioui.org/io/profile"] = map[string]reflect.Value{
		// type definitions
		"Event": reflect.ValueOf((*profile.Event)(nil)),
		"Op":    reflect.ValueOf((*profile.Op)(nil)),
	}
}
