// Code generated by 'yaegi extract gioui.org/font/opentype'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/font/opentype"
	"reflect"
)

func init() {
	Symbols["gioui.org/font/opentype"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Parse":                   reflect.ValueOf(opentype.Parse),
		"ParseCollection":         reflect.ValueOf(opentype.ParseCollection),
		"ParseCollectionReaderAt": reflect.ValueOf(opentype.ParseCollectionReaderAt),

		// type definitions
		"Collection": reflect.ValueOf((*opentype.Collection)(nil)),
		"Font":       reflect.ValueOf((*opentype.Font)(nil)),
	}
}
