// Code generated by 'yaegi extract gioui.org/op'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/op"
	"reflect"
)

func init() {
	Symbols["gioui.org/op"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Affine": reflect.ValueOf(op.Affine),
		"Defer":  reflect.ValueOf(op.Defer),
		"Offset": reflect.ValueOf(op.Offset),
		"Record": reflect.ValueOf(op.Record),
		"Save":   reflect.ValueOf(op.Save),

		// type definitions
		"CallOp":       reflect.ValueOf((*op.CallOp)(nil)),
		"InvalidateOp": reflect.ValueOf((*op.InvalidateOp)(nil)),
		"MacroOp":      reflect.ValueOf((*op.MacroOp)(nil)),
		"Ops":          reflect.ValueOf((*op.Ops)(nil)),
		"StateOp":      reflect.ValueOf((*op.StateOp)(nil)),
		"TransformOp":  reflect.ValueOf((*op.TransformOp)(nil)),
	}
}
