// Code generated by 'yaegi extract gioui.org/app/headless'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/app/headless"
	"reflect"
)

func init() {
	Symbols["gioui.org/app/headless"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewWindow": reflect.ValueOf(headless.NewWindow),

		// type definitions
		"Window": reflect.ValueOf((*headless.Window)(nil)),
	}
}
