// Code generated by 'yaegi extract gioui.org/io/system'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/io/system"
	"reflect"
)

func init() {
	Symbols["gioui.org/io/system"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CommandBack":  reflect.ValueOf(system.CommandBack),
		"StagePaused":  reflect.ValueOf(system.StagePaused),
		"StageRunning": reflect.ValueOf(system.StageRunning),

		// type definitions
		"CommandEvent": reflect.ValueOf((*system.CommandEvent)(nil)),
		"CommandType":  reflect.ValueOf((*system.CommandType)(nil)),
		"DestroyEvent": reflect.ValueOf((*system.DestroyEvent)(nil)),
		"FrameEvent":   reflect.ValueOf((*system.FrameEvent)(nil)),
		"Insets":       reflect.ValueOf((*system.Insets)(nil)),
		"Stage":        reflect.ValueOf((*system.Stage)(nil)),
		"StageEvent":   reflect.ValueOf((*system.StageEvent)(nil)),
	}
}
