// Code generated by 'yaegi extract gioui.org/io/router'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/io/router"
	"reflect"
)

func init() {
	Symbols["gioui.org/io/router"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"TextInputClose": reflect.ValueOf(router.TextInputClose),
		"TextInputKeep":  reflect.ValueOf(router.TextInputKeep),
		"TextInputOpen":  reflect.ValueOf(router.TextInputOpen),

		// type definitions
		"Router":         reflect.ValueOf((*router.Router)(nil)),
		"TextInputState": reflect.ValueOf((*router.TextInputState)(nil)),
	}
}
