// Code generated by 'yaegi extract gioui.org/x/profiling'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/x/profiling"
	"reflect"
)

func init() {
	Symbols["gioui.org/x/profiling"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewRecorder": reflect.ValueOf(profiling.NewRecorder),

		// type definitions
		"CSVTimingRecorder": reflect.ValueOf((*profiling.CSVTimingRecorder)(nil)),
		"Timings":           reflect.ValueOf((*profiling.Timings)(nil)),
	}
}
