// Code generated by 'yaegi extract gioui.org/x/colorpicker'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/x/colorpicker"
	"reflect"
)

func init() {
	Symbols["gioui.org/x/colorpicker"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Mux":         reflect.ValueOf(colorpicker.Mux),
		"NewMuxState": reflect.ValueOf(colorpicker.NewMuxState),
		"Picker":      reflect.ValueOf(colorpicker.Picker),

		// type definitions
		"C":           reflect.ValueOf((*colorpicker.C)(nil)),
		"D":           reflect.ValueOf((*colorpicker.D)(nil)),
		"MuxOption":   reflect.ValueOf((*colorpicker.MuxOption)(nil)),
		"MuxState":    reflect.ValueOf((*colorpicker.MuxState)(nil)),
		"MuxStyle":    reflect.ValueOf((*colorpicker.MuxStyle)(nil)),
		"PickerStyle": reflect.ValueOf((*colorpicker.PickerStyle)(nil)),
		"State":       reflect.ValueOf((*colorpicker.State)(nil)),
	}
}
