// Code generated by 'yaegi extract gioui.org/op/clip'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/op/clip"
	"reflect"
)

func init() {
	Symbols["gioui.org/op/clip"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BevelJoin":    reflect.ValueOf(clip.BevelJoin),
		"FlatCap":      reflect.ValueOf(clip.FlatCap),
		"RoundCap":     reflect.ValueOf(clip.RoundCap),
		"RoundJoin":    reflect.ValueOf(clip.RoundJoin),
		"SquareCap":    reflect.ValueOf(clip.SquareCap),
		"UniformRRect": reflect.ValueOf(clip.UniformRRect),

		// type definitions
		"Border":      reflect.ValueOf((*clip.Border)(nil)),
		"Dash":        reflect.ValueOf((*clip.Dash)(nil)),
		"DashSpec":    reflect.ValueOf((*clip.DashSpec)(nil)),
		"Op":          reflect.ValueOf((*clip.Op)(nil)),
		"Outline":     reflect.ValueOf((*clip.Outline)(nil)),
		"Path":        reflect.ValueOf((*clip.Path)(nil)),
		"PathSpec":    reflect.ValueOf((*clip.PathSpec)(nil)),
		"RRect":       reflect.ValueOf((*clip.RRect)(nil)),
		"Rect":        reflect.ValueOf((*clip.Rect)(nil)),
		"Stroke":      reflect.ValueOf((*clip.Stroke)(nil)),
		"StrokeCap":   reflect.ValueOf((*clip.StrokeCap)(nil)),
		"StrokeJoin":  reflect.ValueOf((*clip.StrokeJoin)(nil)),
		"StrokeStyle": reflect.ValueOf((*clip.StrokeStyle)(nil)),
	}
}
