// Code generated by 'yaegi extract gioui.org/text'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/op"
	"gioui.org/text"
	"golang.org/x/image/math/fixed"
	"io"
	"reflect"
)

func init() {
	Symbols["gioui.org/text"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bold":     reflect.ValueOf(text.Bold),
		"End":      reflect.ValueOf(text.End),
		"Italic":   reflect.ValueOf(text.Italic),
		"Medium":   reflect.ValueOf(text.Medium),
		"Middle":   reflect.ValueOf(text.Middle),
		"NewCache": reflect.ValueOf(text.NewCache),
		"Normal":   reflect.ValueOf(text.Normal),
		"Regular":  reflect.ValueOf(text.Regular),
		"Start":    reflect.ValueOf(text.Start),

		// type definitions
		"Alignment": reflect.ValueOf((*text.Alignment)(nil)),
		"Cache":     reflect.ValueOf((*text.Cache)(nil)),
		"Face":      reflect.ValueOf((*text.Face)(nil)),
		"Font":      reflect.ValueOf((*text.Font)(nil)),
		"FontFace":  reflect.ValueOf((*text.FontFace)(nil)),
		"Layout":    reflect.ValueOf((*text.Layout)(nil)),
		"Line":      reflect.ValueOf((*text.Line)(nil)),
		"Shaper":    reflect.ValueOf((*text.Shaper)(nil)),
		"Style":     reflect.ValueOf((*text.Style)(nil)),
		"Typeface":  reflect.ValueOf((*text.Typeface)(nil)),
		"Variant":   reflect.ValueOf((*text.Variant)(nil)),
		"Weight":    reflect.ValueOf((*text.Weight)(nil)),

		// interface wrapper definitions
		"_Face":   reflect.ValueOf((*_gioui_org_text_Face)(nil)),
		"_Shaper": reflect.ValueOf((*_gioui_org_text_Shaper)(nil)),
	}
}

// _gioui_org_text_Face is an interface wrapper for Face type
type _gioui_org_text_Face struct {
	WLayout func(ppem fixed.Int26_6, maxWidth int, txt io.Reader) ([]text.Line, error)
	WShape  func(ppem fixed.Int26_6, str text.Layout) op.CallOp
}

func (W _gioui_org_text_Face) Layout(ppem fixed.Int26_6, maxWidth int, txt io.Reader) ([]text.Line, error) {
	return W.WLayout(ppem, maxWidth, txt)
}
func (W _gioui_org_text_Face) Shape(ppem fixed.Int26_6, str text.Layout) op.CallOp {
	return W.WShape(ppem, str)
}

// _gioui_org_text_Shaper is an interface wrapper for Shaper type
type _gioui_org_text_Shaper struct {
	WLayout       func(font text.Font, size fixed.Int26_6, maxWidth int, txt io.Reader) ([]text.Line, error)
	WLayoutString func(font text.Font, size fixed.Int26_6, maxWidth int, str string) []text.Line
	WShape        func(font text.Font, size fixed.Int26_6, layout text.Layout) op.CallOp
}

func (W _gioui_org_text_Shaper) Layout(font text.Font, size fixed.Int26_6, maxWidth int, txt io.Reader) ([]text.Line, error) {
	return W.WLayout(font, size, maxWidth, txt)
}
func (W _gioui_org_text_Shaper) LayoutString(font text.Font, size fixed.Int26_6, maxWidth int, str string) []text.Line {
	return W.WLayoutString(font, size, maxWidth, str)
}
func (W _gioui_org_text_Shaper) Shape(font text.Font, size fixed.Int26_6, layout text.Layout) op.CallOp {
	return W.WShape(font, size, layout)
}
