// Code generated by 'yaegi extract gioui.org/f32'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/f32"
	"reflect"
)

func init() {
	Symbols["gioui.org/f32"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewAffine2D": reflect.ValueOf(f32.NewAffine2D),
		"Pt":          reflect.ValueOf(f32.Pt),
		"Rect":        reflect.ValueOf(f32.Rect),

		// type definitions
		"Affine2D":  reflect.ValueOf((*f32.Affine2D)(nil)),
		"Point":     reflect.ValueOf((*f32.Point)(nil)),
		"Rectangle": reflect.ValueOf((*f32.Rectangle)(nil)),
	}
}
