// Code generated by 'yaegi extract gioui.org/font/gofont'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/font/gofont"
	"reflect"
)

func init() {
	Symbols["gioui.org/font/gofont"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Collection": reflect.ValueOf(gofont.Collection),
	}
}
