// Code generated by 'yaegi extract gioui.org/unit'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/unit"
	"reflect"
)

func init() {
	Symbols["gioui.org/unit"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Add":    reflect.ValueOf(unit.Add),
		"Dp":     reflect.ValueOf(unit.Dp),
		"Max":    reflect.ValueOf(unit.Max),
		"Px":     reflect.ValueOf(unit.Px),
		"Sp":     reflect.ValueOf(unit.Sp),
		"UnitDp": reflect.ValueOf(unit.UnitDp),
		"UnitPx": reflect.ValueOf(unit.UnitPx),
		"UnitSp": reflect.ValueOf(unit.UnitSp),

		// type definitions
		"Metric": reflect.ValueOf((*unit.Metric)(nil)),
		"Unit":   reflect.ValueOf((*unit.Unit)(nil)),
		"Value":  reflect.ValueOf((*unit.Value)(nil)),
	}
}
