// Code generated by 'yaegi extract gioui.org/x/outlay'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/x/outlay"
	"reflect"
)

func init() {
	Symbols["gioui.org/x/outlay"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Item": reflect.ValueOf(outlay.Item),

		// type definitions
		"Animation":   reflect.ValueOf((*outlay.Animation)(nil)),
		"Cell":        reflect.ValueOf((*outlay.Cell)(nil)),
		"Fan":         reflect.ValueOf((*outlay.Fan)(nil)),
		"FanItem":     reflect.ValueOf((*outlay.FanItem)(nil)),
		"Grid":        reflect.ValueOf((*outlay.Grid)(nil)),
		"GridElement": reflect.ValueOf((*outlay.GridElement)(nil)),
		"GridWrap":    reflect.ValueOf((*outlay.GridWrap)(nil)),
		"Table":       reflect.ValueOf((*outlay.Table)(nil)),
	}
}
