// Code generated by 'yaegi extract gioui.org/x/haptic'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/x/haptic"
	"reflect"
)

func init() {
	Symbols["gioui.org/x/haptic"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewBuzzer": reflect.ValueOf(haptic.NewBuzzer),

		// type definitions
		"Buzzer": reflect.ValueOf((*haptic.Buzzer)(nil)),
	}
}
