// Code generated by 'yaegi extract gioui.org/x/notify'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/x/notify"
	"reflect"
)

func init() {
	Symbols["gioui.org/x/notify"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewManager": reflect.ValueOf(notify.NewManager),

		// type definitions
		"Manager":      reflect.ValueOf((*notify.Manager)(nil)),
		"Notification": reflect.ValueOf((*notify.Notification)(nil)),
	}
}
