// Code generated by 'yaegi extract gioui.org/gpu'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/gpu"
	"gioui.org/op"
	"image"
	"image/color"
	"reflect"
)

func init() {
	Symbols["gioui.org/gpu"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(gpu.New),

		// type definitions
		"GPU": reflect.ValueOf((*gpu.GPU)(nil)),

		// interface wrapper definitions
		"_GPU": reflect.ValueOf((*_gioui_org_gpu_GPU)(nil)),
	}
}

// _gioui_org_gpu_GPU is an interface wrapper for GPU type
type _gioui_org_gpu_GPU struct {
	WClear   func(color color.NRGBA)
	WCollect func(viewport image.Point, frame *op.Ops)
	WFrame   func() error
	WProfile func() string
	WRelease func()
}

func (W _gioui_org_gpu_GPU) Clear(color color.NRGBA)                     { W.WClear(color) }
func (W _gioui_org_gpu_GPU) Collect(viewport image.Point, frame *op.Ops) { W.WCollect(viewport, frame) }
func (W _gioui_org_gpu_GPU) Frame() error                                { return W.WFrame() }
func (W _gioui_org_gpu_GPU) Profile() string                             { return W.WProfile() }
func (W _gioui_org_gpu_GPU) Release()                                    { W.WRelease() }
