// Code generated by 'yaegi extract gioui.org/x/eventx'. DO NOT EDIT.

package giopkgs

import (
	"gioui.org/x/eventx"
	"reflect"
)

func init() {
	Symbols["gioui.org/x/eventx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Combine": reflect.ValueOf(eventx.Combine),
		"Enspy":   reflect.ValueOf(eventx.Enspy),

		// type definitions
		"CombinedQueue": reflect.ValueOf((*eventx.CombinedQueue)(nil)),
		"EventGroup":    reflect.ValueOf((*eventx.EventGroup)(nil)),
		"Spy":           reflect.ValueOf((*eventx.Spy)(nil)),
	}
}
